/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServersIndexRouteImport } from './routes/servers/index'
import { Route as ServersServerIdRouteImport } from './routes/servers/$serverId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminNodesRouteImport } from './routes/admin/nodes'
import { Route as AdminEggsRouteImport } from './routes/admin/eggs'
import { Route as ServersServerIdIndexRouteImport } from './routes/servers/$serverId/index'
import { Route as ServersServerIdSettingsRouteImport } from './routes/servers/$serverId/settings'
import { Route as ServersServerIdFilesRouteImport } from './routes/servers/$serverId/files'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersIndexRoute = ServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersServerIdRoute = ServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNodesRoute = AdminNodesRouteImport.update({
  id: '/admin/nodes',
  path: '/admin/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEggsRoute = AdminEggsRouteImport.update({
  id: '/admin/eggs',
  path: '/admin/eggs',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersServerIdIndexRoute = ServersServerIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServersServerIdRoute,
} as any)
const ServersServerIdSettingsRoute = ServersServerIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ServersServerIdRoute,
} as any)
const ServersServerIdFilesRoute = ServersServerIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ServersServerIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/eggs': typeof AdminEggsRoute
  '/admin/nodes': typeof AdminNodesRoute
  '/admin/users': typeof AdminUsersRoute
  '/servers/$serverId': typeof ServersServerIdRouteWithChildren
  '/servers/': typeof ServersIndexRoute
  '/servers/$serverId/files': typeof ServersServerIdFilesRoute
  '/servers/$serverId/settings': typeof ServersServerIdSettingsRoute
  '/servers/$serverId/': typeof ServersServerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/eggs': typeof AdminEggsRoute
  '/admin/nodes': typeof AdminNodesRoute
  '/admin/users': typeof AdminUsersRoute
  '/servers': typeof ServersIndexRoute
  '/servers/$serverId/files': typeof ServersServerIdFilesRoute
  '/servers/$serverId/settings': typeof ServersServerIdSettingsRoute
  '/servers/$serverId': typeof ServersServerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/eggs': typeof AdminEggsRoute
  '/admin/nodes': typeof AdminNodesRoute
  '/admin/users': typeof AdminUsersRoute
  '/servers/$serverId': typeof ServersServerIdRouteWithChildren
  '/servers/': typeof ServersIndexRoute
  '/servers/$serverId/files': typeof ServersServerIdFilesRoute
  '/servers/$serverId/settings': typeof ServersServerIdSettingsRoute
  '/servers/$serverId/': typeof ServersServerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/eggs'
    | '/admin/nodes'
    | '/admin/users'
    | '/servers/$serverId'
    | '/servers/'
    | '/servers/$serverId/files'
    | '/servers/$serverId/settings'
    | '/servers/$serverId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/eggs'
    | '/admin/nodes'
    | '/admin/users'
    | '/servers'
    | '/servers/$serverId/files'
    | '/servers/$serverId/settings'
    | '/servers/$serverId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/admin/eggs'
    | '/admin/nodes'
    | '/admin/users'
    | '/servers/$serverId'
    | '/servers/'
    | '/servers/$serverId/files'
    | '/servers/$serverId/settings'
    | '/servers/$serverId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AdminEggsRoute: typeof AdminEggsRoute
  AdminNodesRoute: typeof AdminNodesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ServersServerIdRoute: typeof ServersServerIdRouteWithChildren
  ServersIndexRoute: typeof ServersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/': {
      id: '/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof ServersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$serverId': {
      id: '/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ServersServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/nodes': {
      id: '/admin/nodes'
      path: '/admin/nodes'
      fullPath: '/admin/nodes'
      preLoaderRoute: typeof AdminNodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eggs': {
      id: '/admin/eggs'
      path: '/admin/eggs'
      fullPath: '/admin/eggs'
      preLoaderRoute: typeof AdminEggsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$serverId/': {
      id: '/servers/$serverId/'
      path: '/'
      fullPath: '/servers/$serverId/'
      preLoaderRoute: typeof ServersServerIdIndexRouteImport
      parentRoute: typeof ServersServerIdRoute
    }
    '/servers/$serverId/settings': {
      id: '/servers/$serverId/settings'
      path: '/settings'
      fullPath: '/servers/$serverId/settings'
      preLoaderRoute: typeof ServersServerIdSettingsRouteImport
      parentRoute: typeof ServersServerIdRoute
    }
    '/servers/$serverId/files': {
      id: '/servers/$serverId/files'
      path: '/files'
      fullPath: '/servers/$serverId/files'
      preLoaderRoute: typeof ServersServerIdFilesRouteImport
      parentRoute: typeof ServersServerIdRoute
    }
  }
}

interface ServersServerIdRouteChildren {
  ServersServerIdFilesRoute: typeof ServersServerIdFilesRoute
  ServersServerIdSettingsRoute: typeof ServersServerIdSettingsRoute
  ServersServerIdIndexRoute: typeof ServersServerIdIndexRoute
}

const ServersServerIdRouteChildren: ServersServerIdRouteChildren = {
  ServersServerIdFilesRoute: ServersServerIdFilesRoute,
  ServersServerIdSettingsRoute: ServersServerIdSettingsRoute,
  ServersServerIdIndexRoute: ServersServerIdIndexRoute,
}

const ServersServerIdRouteWithChildren = ServersServerIdRoute._addFileChildren(
  ServersServerIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AdminEggsRoute: AdminEggsRoute,
  AdminNodesRoute: AdminNodesRoute,
  AdminUsersRoute: AdminUsersRoute,
  ServersServerIdRoute: ServersServerIdRouteWithChildren,
  ServersIndexRoute: ServersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
